[package]
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"
name = "modtorio"
version = "0.1.0"

[dependencies]
anyhow = "1.0.28"
serde_json = "1.0.51"

[dependencies.serde]
features = ["derive"]
version = "1.0.106"
