[package]
name = "util"
version = "0.1.0"
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
regex = "1.3.7"
lazy_static = "1.4.0"

[dependencies.serde]
version = "1.0.106"
features = ["derive"]
