[package]
authors = ["Spanfile <spansdev@gmail.com>"]
description = "Various derive macros for Modtorio."
edition = "2018"
name = "derive"
version = "0.1.0"

[dependencies]
heck = "0.3.1"
proc-macro2 = "1.0.19"
quote = "1.0.7"
syn = "1.0.38"
thiserror = "1.0.20"

[lib]
proc-macro = true
