[package]
name = "derive"
version = "0.1.0"
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"

[dependencies]
syn = "1.0.34"
quote = "1.0.7"
thiserror = "1.0.20"
proc-macro2 = "1.0.18"
heck = "0.3.1"

[lib]
proc-macro = true
