[package]
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"
name = "modtorio"
version = "0.1.0"

[dependencies]
anyhow = "1.0.28"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
serde_with = "1.4.0"
zip = { git = "https://github.com/Spanfile/zip-rs.git" }
glob = "0.3.0"
regex = "1.3.7"
lazy_static = "1.4.0"
fern = { version = "0.6.0", features = ["colored"] }
log = "0.4.8"
url = "2.1.1"
bytes = "0.5.4"
reqwest = { version = "0.10.4", features = ["json"] }
tokio = { version = "0.2.20", features = ["full"] }
futures = "0.3.5"
envy = "0.4.1"
dotenv = "0.15.0"
async-trait = "0.1.30"
tempfile = "3.1.0"
chrono = { version = "0.4.11", features = ["serde"] }
bytesize = "1.0.0"
rustorm = { version = "0.17.0", features = ["with-sqlite"] }
rustorm_dao = "0.5.0"
num-traits = "0.2.11"
num-derive = "0.3.0"

macros = { path = "../macros" }
