[package]
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"
name = "modtorio"
version = "0.1.0"

[dependencies]
anyhow = "1.0.28"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
zip = "0.5.5"
glob = "0.3.0"
regex = "1.3.7"
lazy_static = "1.4.0"
fern = { version = "0.6.0", features = ["colored"] }
log = "0.4.8"
isahc = { version = "0.9.1", features = ["json"] }
url = "2.1.1"
http = "0.2.1"
macros = { path = "../macros" }
ext = { path = "../ext" }
util = { path = "../util" }
